DROP DATABASE IF EXISTS Customer_Reviews;

CREATE DATABASE Customer_Reviews;

USE Customer_Reviews;

CREATE TABLE deals (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  username varchar(100) NOT NULL,
  reviews_count int NOT NULL,
  top_reviewer int NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE reviews (
  id int NOT NULL AUTO_INCREMENT,
  deals_id int NOT NULL,
  user_id int NOT NULL,
  reviews_score smallint NOT NULL,
  review_text varchar (2000) NOT NULL,
  review_date datetime NOT NULL,
  relevancy_score int NOT NULL,
  helpful_score int NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY deals_id REFERENCES deals(id),
  FOREIGN KEY user_id REFERENCES users(id)
);

-- Add experiences... shared across the group

INSERT INTO deals (name) VALUES ('River Sightseeing or Sunset Tour for One or Two People from Charles Riverboat Company')
INSERT INTO deals (name) VALUES ('Platinum Wash with Rain-X Wheel and Windshield Treatment')
INSERT INTO deals (name) VALUES ('Three Hour DIY Sculpting Class for One, Two, or Four at Play With Clay')
INSERT INTO deals (name) VALUES ('Bread-Making Class for One, Two, or Four at Sour Flour')
INSERT INTO deals (name) VALUES ('Painting Experiences at Muse Paintbar')
INSERT INTO deals (name) VALUES ('Splashtown Water Park Visit for Two at Funtown Splashtown USA')
INSERT INTO deals (name) VALUES ('Whale-Watching Cruise for One, Two, or Four from Cape Ann Whale Watch')
INSERT INTO deals (name) VALUES ('General Admission for Two or Four to King Richard\'s Faire')
INSERT INTO deals (name) VALUES ('Distillery Tour and Etched Glencairn Whiskey Glasses for Two or Four at New England Distilling')
INSERT INTO deals (name) VALUES ('One Hour of Unlimited Bowling for Up to Four or Eight at Jimmy the Greek\'s Bowling and Arcade')
INSERT INTO deals (name) VALUES ('All-Day Fishing Trip for 1 or 2 with Rod Rental from Al Gauron Deep Sea Fishing & Whale Watching')
INSERT INTO deals (name) VALUES ('Full-Day Waterfall Rappelling for One, Two, or Four at North Ridge Mountain Guides')
INSERT INTO deals (name) VALUES ('Beer Tasting and Pint Glasses for Two, Four, or Six at Kennebec River Pub and Brewery')
INSERT INTO deals (name) VALUES ('Half-Day Rock-Climbing Trip for Two, Three, or Four from Acadia Mountain Guides Climbing School')
INSERT INTO deals (name) VALUES ('Premium Adventure for One Adult, Youth or Senior at Gunstock Mountain Resort')
INSERT INTO deals (name) VALUES ('Zipline Adventure Course Admission for Two or Four at Monkey Trunks Chocorua')
INSERT INTO deals (name) VALUES ('Axe Throwing for 6 or 12 People at Northern Axperts')
INSERT INTO deals (name) VALUES ('Beginner\'s Salsa-Dancing Course from SkillSuccess')
INSERT INTO deals (name) VALUES ('Beginner-Ukulele Online Course from SkillSuccess')
INSERT INTO deals (name) VALUES ('Zipline Canopy Tour for One at Provo Canyon Adventures')
INSERT INTO deals (name) VALUES ('Two or Four One-Hour Jump Passes at Airborne Trampoline Arena')
INSERT INTO deals (name) VALUES ('60-Minute Float Therapy Sessions at True Rest Float Spa')
INSERT INTO deals (name) VALUES ('Month of Unlimited Classes Including Yoga, Hot Yoga, Barre at Mountain Yoga Sandy')
INSERT INTO deals (name) VALUES ('One 60-Minute Massage at Aribella Salon and Spa')
INSERT INTO deals (name) VALUES ('Turnagain Arm and Alaska Wildlife Tour from Anchorage')
INSERT INTO deals (name) VALUES ('Anchorage to Seward Cruise Transfer and Private Tour')
INSERT INTO deals (name) VALUES ('Jump Passes or Party at Get Air')
INSERT INTO deals (name) VALUES ('Anchorage City Tour with Alaska Native Heritage Center')
INSERT INTO deals (name) VALUES ('Juneau Shore Excursion: Whale-Watching Excursion')
INSERT INTO deals (name) VALUES ('Admission for One Child or Adult to Aquarium of the Bay')
INSERT INTO deals (name) VALUES ('First-Aid, CPR, and AED Certification Course from Advanced Medical Certification')
INSERT INTO deals (name) VALUES ('Afternoon Sail, Dinner Cruise, or Snorkeling & Lunch Sail for a Child or Adult from Makani Catamaran')
INSERT INTO deals (name) VALUES ('One Hour Evening Manta Snorkeling for One or Two at Hawaii Island And Ocean Tours')
INSERT INTO deals (name) VALUES ('Semi-Private and Private Surf Lessons at Moku Surf Rentals & Board Shop')
INSERT INTO deals (name) VALUES ('Catamaran TradeWind Sailing Trip for Two, Four, or Six from Maita`i Catamaran')
INSERT INTO deals (name) VALUES ('25-minute RHS Distillery Micro Tour and Tasting with Optional Take-Home Bottle at RHS Distillery')
INSERT INTO deals (name) VALUES ('Maui Sunset Dinner Cruise')
INSERT INTO deals (name) VALUES ('Guided Kayak Tour with Snorkeling and Lunch or Kayak Rental for One or Two from Twogood Kayaks')
INSERT INTO deals (name) VALUES ('Dolphin Snorkeling Tour for One, Two, or Four at EO Waianae Tours')
INSERT INTO deals (name) VALUES ('Pearl Harbor & Arizona Memorial Tour with Transportation from Aloha Pearl Harbor Tour')
INSERT INTO deals (name) VALUES ('Resurrection Bay Cruise with Fox Island')
INSERT INTO deals (name) VALUES ('Full-Day Tour or Overnight Trip from Miller Landing')
INSERT INTO deals (name) VALUES ('Alaskan Bush Plane Piloting Experience with In-flight Instruction at Legends Alaska')
INSERT INTO deals (name) VALUES ('90-Minute Scenic Trail Ride for Two or Four at Sunderland Ranch')
INSERT INTO deals (name) VALUES ('Nenana Gorge Whitewater Rafting - Oar Option')
INSERT INTO deals (name) VALUES ('Anchorage Northern Lights Tour')
INSERT INTO deals (name) VALUES ('Grand Denali Flightseeing tour from Talkeetna')
INSERT INTO deals (name) VALUES ('Helicopter and Glacier Dogsled Tour')
INSERT INTO deals (name) VALUES ('18-Hole Extreme Mini-Golf Round or Extreme Fun Pass for Two, Four, or Six at Putters Wild')
INSERT INTO deals (name) VALUES ('2015 Vespa Primavera 150 Scooter at Rockridge Two Wheels and Vespa Walnut Creek')
INSERT INTO deals (name) VALUES ('Epic Day on The Bay! Create your own extreme yacht party with Flyboarding, Zorbing and more!')
INSERT INTO deals (name) VALUES ('Ground School and Tandem Jump for One, Two, or Four from 9,000 or 13,000 Feet from Skydive Sacramento')
INSERT INTO deals (name) VALUES ('Pool Day or Rental from Sapphire Pool & Day Club')
INSERT INTO deals (name) VALUES ('Helicopter Tour at Specialized Helicopters')
INSERT INTO deals (name) VALUES ('Wine Tours with Champagne for Up to 8, 12, or 14 Passengers from Event And Tours')
INSERT INTO deals (name) VALUES ('8 Hour Private Sonoma or Napa Wine Tasting Tour (Sedan, SUV or Limo)')
INSERT INTO deals (name) VALUES ('Winery Tour in Limousine, SUV, Limousine Bus, or Sprinter from Event Logistic')
INSERT INTO deals (name) VALUES ('Five Hours of Large-Group Luxury Transportation from Edda Limousine Service')
INSERT INTO deals (name) VALUES ('Private Daytime or Night Food Tour for Up to 10 People at Team Building Food Tours')
INSERT INTO deals (name) VALUES ('Six-Hour Day Camp')
INSERT INTO deals (name) VALUES ('Three-Hour Boat Tour for Three or Eight-Hour Private Boat Tour for Six from Bay Expeditions')
INSERT INTO deals (name) VALUES ('Three-Hour Guided Electric Bike Tour For Eight People from Eco Bike Adventures')
INSERT INTO deals (name) VALUES ('Introductory Flight Course for One or Two People')
INSERT INTO deals (name) VALUES ('Half- or Full-Day Fishing Trip of Choice for Up to Two')
INSERT INTO deals (name) VALUES ('Two-Hour Yacht Charter for Up to Six with America Cup Charters')
INSERT INTO deals (name) VALUES ('Two, Four, or Six Tours of Surfing Goat Dairy')
INSERT INTO deals (name) VALUES ('Haleakala Maui Zipline Tour for One, Two, or Four at Skyline Eco-Adventures')
INSERT INTO deals (name) VALUES ('Afternoon Sail, Dinner Cruise, or Snorkeling & Lunch Sail for a Child or Adult from Makani Catamaran')
INSERT INTO deals (name) VALUES ('Amazing Comic Con Aloha Admission on August 24, 25, or 26')
INSERT INTO deals (name) VALUES ('One, Two, or Four Tickets to USS Bowfin Submarine Museum & Park')
INSERT INTO deals (name) VALUES ('Two-Hour Guided Kayak Tour for One or Two from San Francisco Kayak & Adventures')
INSERT INTO deals (name) VALUES ('Performance Hybrid Bicycle Rental for One, Two, or Four at Bay City Bike')
INSERT INTO deals (name) VALUES ('Ticket for Any Sailing Tour at San Francisco Sailing Company')
INSERT INTO deals (name) VALUES ('San Francisco Cannabis Walking Tour for One, Two, or Four at Explore San Francisco')
INSERT INTO deals (name) VALUES ('Patriot Jet Boat Thrill Ride for One, Two, or Four at Flagship Cruises & Events')
INSERT INTO deals (name) VALUES ('Whale Watching and Dolphin Cruise from Davey\'s Locker')
INSERT INTO deals (name) VALUES ('90-Minute Passes, Urban Tot or Early Bird, at Uptown Jungle Fun Park')
INSERT INTO deals (name) VALUES ('Wash and Cut with Tossle Dry or with All-Over Color or Partial Highlights at Fantastic Sams')
INSERT INTO deals (name) VALUES ('One-Hour Shooting-Range Package for Two at P2K Range')
INSERT INTO deals (name) VALUES ('Pirates Dinner Adventure in Buena Park for One Adult or Child')
INSERT INTO deals (name) VALUES ('General Admission for One, Two, or Four to The Wave Waterpark ')
INSERT INTO deals (name) VALUES ('Online Driver\'s Ed with DMV Completion Certificate from MyCaliforniaPermit.com')
INSERT INTO deals (name) VALUES ('Two-Hour Harbor Tour for One, Two, or Four from Flagship Cruises and Events')
INSERT INTO deals (name) VALUES ('Round Trip Boat Ride to Catalina Island on The Catalina Flyer from Newport Beach ')
INSERT INTO deals (name) VALUES ('Oil Change at SynFast Oil Change')
INSERT INTO deals (name) VALUES ('8 Pilates Classes at Pilates Room Studios')
INSERT INTO deals (name) VALUES ('Two, Three, Four, Five, or Seven Days of Airport or Seaport Parking at Laurel Parking')
INSERT INTO deals (name) VALUES ('Two Days of Airport Parking at Aladdin Airport Parking')
INSERT INTO deals (name) VALUES ('Brazilian or Bikini Wax at Gigi\'s Beauty Boutique')
INSERT INTO deals (name) VALUES ('Two Craft Beers and a Slice of Pizza at Berkeley Pizza')
INSERT INTO deals (name) VALUES ('One or Three Eyebrow Threading Sessions at Brazilia Skin Care')
INSERT INTO deals (name) VALUES ('Four-Week Medical Weight-Loss Package at Empower Weight Loss')
INSERT INTO deals (name) VALUES ('One Consultation with Exam and One or Two Adjustments at Well-Balanced Chiropractic')
INSERT INTO deals (name) VALUES ('Argentinian Cuisine for Dinner or Lunch at Puerto La Boca')
INSERT INTO deals (name) VALUES ('One 60-Minute Full-Body Massage at Relaxing Massage')
INSERT INTO deals (name) VALUES ('One or Two Months of Unlimited Classes at Yoga Six')
INSERT INTO deals (name) VALUES ('Semi or Full Synthetic Oil-Change Package at Precision Tune Auto Care')
INSERT INTO deals (name) VALUES ('Two-Hour Harbor Cruise for One, Two, or Four at Hornblower San Diego')
INSERT INTO deals (name) VALUES ('Snorkel Package Rental for 1 or 2, or Spearfishing Package Rental for 2 at La Jolla Water Sports')
INSERT INTO deals (name) VALUES ('Eyebrow Threading — My Brow')

-- 50 reviewers, 465 Reviews, more than 13 reviews makes top_reviewer true

INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Ophelie Sanz", 6, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Ellerey Hadigate", 14, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Celina Ackers", 5, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Dallon Youster", 5, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Silvain Radin", 13, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Ebeneser Soames", 5, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Annice Loyndon", 17, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Athene Kerford", 7, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Gillie Carlozzi", 11, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Karim McGrey", 14, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Jacinta Jebb", 16, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Stephanus Steynor", 3, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Marline Aire", 2, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Bernadene Anglish", 9, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Cindelyn Killock", 1, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Nathan Olivazzi", 7, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Guenna Fairbourn", 2, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Mela Windrus", 18, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Ula Sawley", 14, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Shannen Ickov", 4, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Cecilla Coote", 3, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Dag Heine", 5, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Missie Scedall", 12, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Dania Peters", 12, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Donnie Mayne", 5, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Baron Deport", 13, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Lucila Crosser", 8, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Godard Verrier", 7, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Libbie Lambshine", 3, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Eda Connold", 8, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Doug Quogan", 15, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Rock Falconer", 8, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Danie Seelbach", 11, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Isabelita Grahlman", 3, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Yoshiko Champ", 14, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Liza Tieraney", 13, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Rochelle Bouskill", 17, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Gerardo Pattullo", 14, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Dagmar Merrin", 10, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Kirbee Rosingdall", 4, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Chaddie Males", 1, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Yehudit Musso", 12, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Diarmid Batisse", 7, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Giulietta Kigelman", 17)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Horten Woodyer", 6, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Teressa Woodyer", 2, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Delmore Marshalleck", 17)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Lanie Igonet", 17, 1)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Hope Hatcliffe", 13, 0)
INSERT INTO users (username, reviews_count, top_reviewer) VALUES ("Nikolai Inkin", 15, 1)
